import type { Metadata } from "next";
import Link from "next/link";
import LegalPageLayout from "@/components/layout/LegalPageLayout";
import { createPageMetadata } from "@/lib/seo";

export const metadata: Metadata = createPageMetadata({
  title: "AI Content Policy",
  description:
    "TrendsMix AI content policy detailing how artificial intelligence may be used in story creation, editorial review requirements, and our transparency commitments.",
  path: "/ai-policy",
});

export default function AiPolicyPage() {
  return (
    <LegalPageLayout title="AI Content Policy" lastUpdated="2026-07-09">
      <p>
        As artificial intelligence becomes increasingly integrated into creative
        workflows, TrendsMix is committed to transparency about how AI
        technology intersects with the content we publish. This policy outlines
        our position on AI-generated and AI-assisted content, and the standards
        we apply to maintain trust, quality, and authenticity.
      </p>

      <section aria-labelledby="ai-position">
        <h2 id="ai-position" className="text-xl font-semibold text-white">
          1. Our Position on AI in Creative Writing
        </h2>
        <p className="mt-4">
          TrendsMix values human creativity, voice, and originality above all.
          We believe the most compelling fiction emerges from lived experience,
          imagination, and deliberate craft. At the same time, we recognise that
          AI tools can serve as aids in the creative process — much like
          spell-checkers, grammar tools, and research assistants have for
          decades.
        </p>
      </section>

      <section aria-labelledby="ai-what-we-accept">
        <h2 id="ai-what-we-accept" className="text-xl font-semibold text-white">
          2. What We Accept
        </h2>

        <h3 className="mt-5 text-base font-semibold text-zinc-200">
          2.1 AI-Assisted Content
        </h3>
        <p className="mt-3">
          We accept stories where AI tools have been used as part of the
          creative process — for example, brainstorming, outlining, grammar
          checking, or refining prose — provided the author has exercised
          meaningful creative control and editorial judgement over the final
          work.
        </p>

        <h3 className="mt-5 text-base font-semibold text-zinc-200">
          2.2 AI-Generated Content (With Restrictions)
        </h3>
        <p className="mt-3">
          Stories that are substantially generated by AI (where the majority of
          the narrative text is machine-produced) are only accepted when:
        </p>
        <ul className="mt-3 list-disc space-y-2 pl-5">
          <li>The author has substantially edited, shaped, and refined the output.</li>
          <li>The submission demonstrates genuine creative intent and human judgement.</li>
          <li>The author discloses the use of AI in the submission process.</li>
        </ul>
      </section>

      <section aria-labelledby="ai-what-we-reject">
        <h2 id="ai-what-we-reject" className="text-xl font-semibold text-white">
          3. What We Do Not Accept
        </h2>
        <p className="mt-4">We will not publish:</p>
        <ul className="mt-3 list-disc space-y-2 pl-5">
          <li>
            Unedited, raw AI output submitted as a finished story without
            meaningful human authorship.
          </li>
          <li>
            Content generated by AI that is submitted without disclosure of AI
            involvement.
          </li>
          <li>
            AI-generated content that infringes on copyrighted works, plagiarises
            existing stories, or replicates another author&apos;s distinctive
            voice or style.
          </li>
        </ul>
      </section>

      <section aria-labelledby="ai-editorial-review">
        <h2 id="ai-editorial-review" className="text-xl font-semibold text-white">
          4. Editorial Review Standards
        </h2>
        <p className="mt-4">
          All content published on TrendsMix — regardless of whether AI tools
          were involved — passes through our full editorial pipeline as described
          in our{" "}
          <Link href="/editorial-policy" className="text-orange-400 underline decoration-orange-400/30 underline-offset-2 transition-colors hover:text-orange-300">
            Editorial Policy
          </Link>
          . Our editors evaluate every submission on the same criteria: narrative
          quality, originality, emotional resonance, and adherence to our content
          standards.
        </p>
        <p className="mt-3">
          AI involvement does not grant a submission preferential or
          disadvantaged treatment. The work must stand on its own merits.
        </p>
      </section>

      <section aria-labelledby="ai-transparency">
        <h2 id="ai-transparency" className="text-xl font-semibold text-white">
          5. Transparency &amp; Disclosure
        </h2>
        <p className="mt-4">
          Transparency is fundamental to reader trust. Our commitments:
        </p>
        <ul className="mt-3 list-disc space-y-2 pl-5">
          <li>
            Authors are required to disclose significant AI involvement during
            the submission process.
          </li>
          <li>
            Where AI has played a substantial role in content creation, we may
            include a disclosure note alongside the published work.
          </li>
          <li>
            Platform-level content (metadata, descriptions, marketing copy) that
            is AI-assisted will be reviewed and approved by our team before
            publication.
          </li>
        </ul>
      </section>

      <section aria-labelledby="ai-reader-trust">
        <h2 id="ai-reader-trust" className="text-xl font-semibold text-white">
          6. Reader Trust
        </h2>
        <p className="mt-4">
          We understand that readers come to TrendsMix for authentic, quality
          storytelling. This policy exists to ensure that AI serves as a tool in
          service of human creativity — not a replacement for it. If you have
          concerns about any content on our platform, please{" "}
          <Link href="/contact" className="text-orange-400 underline decoration-orange-400/30 underline-offset-2 transition-colors hover:text-orange-300">
            contact us
          </Link>
          .
        </p>
      </section>

      <section aria-labelledby="ai-evolution">
        <h2 id="ai-evolution" className="text-xl font-semibold text-white">
          7. Policy Evolution
        </h2>
        <p className="mt-4">
          The landscape of AI and creative writing is evolving rapidly. We will
          review and update this policy regularly to reflect new developments,
          industry best practices, and feedback from our community. Material
          changes will be noted with an updated date at the top of this page.
        </p>
      </section>
    </LegalPageLayout>
  );
}
